Repository openshift/openshift-logos-icon, pull requests merged in 2018-04, with the labels that each got.

#13 Add Xamarin logo
  demo-files/demo.css
  demo-files/demo.js
  demo.html
  fonts/openshift-logos-icon.svg
  fonts/openshift-logos-icon.ttf
  fonts/openshift-logos-icon.woff
  less/openshift-logos-icon.less
  less/variables.less
  selection.json
  style.css
Labels: size/M

#14 Add kubevirt and mssql
  demo.html
  fonts/openshift-logos-icon.svg
  fonts/openshift-logos-icon.ttf
  fonts/openshift-logos-icon.woff
  less/openshift-logos-icon.less
  less/variables.less
  selection.json
  style.css
Labels: size/L

#15 Bump version to v1.5.0
  bower.json
  package.json
  selection.json
Labels: size/XS

#16 Add VM icons
  demo.html
  fonts/openshift-logos-icon.svg
  fonts/openshift-logos-icon.ttf
  fonts/openshift-logos-icon.woff
  less/openshift-logos-icon.less
  less/variables.less
  selection.json
  style.css
Labels: size/XL

#17 Bump version to v1.6.0
  bower.json
  package.json
Labels: size/XS
